import { parseArgs } from "node:util";
import { existsSync, copyFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, basename, extname } from "node:path";
import { createRequire } from "node:module";
import process from "node:process";
import { runZig, errMessage } from "./zig.js";

const BUILD_HELP = `zignapi build — build the addon in the current directory

Usage:
  zignapi build [--release]

Options:
  --release   Optimize the build (-Doptimize=ReleaseFast)
  -h, --help  Show this help

Runs "zig build" in the current directory, copies the resulting shared library
to ./<name>.node (renaming a plain .dylib/.so/.dll if needed), then generates
index.js and index.d.ts from the addon's embedded type declarations.
`;

export async function runBuild(argv: string[]): Promise<void> {
  const { values } = parseArgs({
    args: argv,
    options: {
      release: { type: "boolean", default: false },
      help: { type: "boolean", short: "h", default: false },
    },
  });

  if (values.help) {
    process.stdout.write(BUILD_HELP);
    return;
  }

  const cwd = process.cwd();
  if (!existsSync(join(cwd, "build.zig"))) {
    throw new Error("no build.zig found in the current directory");
  }

  const zigArgs = ["build"];
  if (values.release) zigArgs.push("-Doptimize=ReleaseFast");

  runZig(cwd, zigArgs, { repairZon: join(cwd, "build.zig.zon") });

  // Locate the freshly built addon and copy it to ./<name>.node.
  const addonPath = findAddon(join(cwd, "zig-out"));
  if (!addonPath) {
    throw new Error(
      "build succeeded but no addon (.node or shared library) was found under zig-out",
    );
  }

  const nodeFile = addonName(addonPath);
  copyFileSync(addonPath, join(cwd, nodeFile));
  process.stdout.write(`✔ built ${nodeFile}\n`);

  generateBindings(cwd, nodeFile);
}

/**
 * Emit `index.js` (a loader that re-exports the addon) and `index.d.ts` (the
 * TypeScript declarations) from the type info the addon embeds as
 * `__zignapi_dts__`. Non-fatal: a build that can't be introspected still counts
 * as a successful build.
 */
function generateBindings(cwd: string, nodeFile: string): void {
  const require = createRequire(import.meta.url);
  let addon: Record<string, unknown>;
  try {
    addon = require(join(cwd, nodeFile)) as Record<string, unknown>;
  } catch (err) {
    process.stderr.write(
      `note: skipped type generation (could not load ${nodeFile}: ${errMessage(err)})\n`,
    );
    return;
  }

  const dts = addon.__zignapi_dts__;
  if (typeof dts !== "string" || dts.length === 0) {
    process.stderr.write("note: addon has no embedded type info; skipping index.d.ts\n");
    return;
  }

  writeFileSync(join(cwd, "index.d.ts"), `// Generated by zignapi — do not edit.\n\n${dts}`);
  writeFileSync(
    join(cwd, "index.js"),
    `"use strict";\n` +
      `const addon = require("./${nodeFile}");\n` +
      `const { __zignapi_dts__, ...api } = addon;\n` +
      `module.exports = api;\n`,
  );
  process.stdout.write("✔ generated index.js + index.d.ts\n");
}

/**
 * Find the built addon under zig-out. Prefers an already-named `.node`,
 * falling back to the first shared library it finds.
 */
function findAddon(dir: string): string | null {
  const nodes: string[] = [];
  const libs: string[] = [];
  const walk = (d: string): void => {
    if (!existsSync(d)) return;
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, entry.name);
      if (entry.isDirectory()) {
        walk(p);
      } else if (entry.isFile()) {
        if (entry.name.endsWith(".node")) nodes.push(p);
        else if (/\.(dylib|so|dll)$/.test(entry.name)) libs.push(p);
      }
    }
  };
  walk(dir);
  return nodes[0] ?? libs[0] ?? null;
}

/** The `<name>.node` filename to copy an addon to at the project root. */
function addonName(addon: string): string {
  if (extname(addon) === ".node") return basename(addon);
  // libfoo.dylib -> foo.node
  let name = basename(addon, extname(addon));
  if (name.startsWith("lib")) name = name.slice(3);
  return `${name}.node`;
}
